### ISSUE TITLE
Update SegmentedControl to Picker

### ISSUE THREAD

**Issue by gbdavid2** [nsscreencast/397-swiftui-tip-calculator#1]
As of Beta 7, SegmentedControl is no longer valid, you need to update it to Picker. e.g.

`private var segmentedTipPercentages: some View {
        Picker(selection: $selectedTipPercentage, label: Text("Tip Percentages")) {
            ForEach(0..<tipPercentages.count) { index in
                Text(self.formatPercent(self.tipPercentages[index])).tag(index)
            }
        }
    }`

**Comment by subdigital** [comment]
Thanks! I'll get this updated.

**Comment by subdigital** [comment]
Done.
